CROP_PREDICTTIONS

In [2]:
import pandas as pd 
from sklearn.tree import DecisionTreeClassifier as dss
link="S:\\ML\\Kaggle_dataset\\Crop_recommendation.csv"
df=pd.read_csv(link)
df.head()

   temperature   humidity        ph  water availability season label
0    20.879744  82.002744  6.502985          202.935536  rainy  rice
1    21.770462  80.319644  7.038096          226.655537  rainy  rice
2    23.004459  82.320763  7.840207          263.964248  rainy  rice
3    26.491096  80.158363  6.980401          242.864034  rainy  rice
4    20.130175  81.604873  7.628473          262.717340  rainy  rice

In [3]:
from sklearn.preprocessing import OneHotEncoder as tvs
from scipy.sparse import hstack
numer=tvs()
values=df.drop(['season','label'],axis=1)
text=numer.fit_transform(df[['season']])
edited =hstack([text,values])
values

      temperature   humidity        ph  water availability
0       20.879744  82.002744  6.502985          202.935536
1       21.770462  80.319644  7.038096          226.655537
2       23.004459  82.320763  7.840207          263.964248
3       26.491096  80.158363  6.980401          242.864034
4       20.130175  81.604873  7.628473          262.717340
...           ...        ...       ...                 ...
1395    23.874845  86.792613  6.718725          177.514731
1396    23.928879  88.071123  6.880205          154.660874
1397    24.814412  81.686889  6.861069          190.788639
1398    24.447439  82.286484  6.769346          190.968489
1399    26.574217  73.819949  7.261581          159.322307

[1400 rows x 4 columns]

In [ ]:
x=edited
y=df['label']
model=dss()
model.fit(x,y)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().